import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../shared/domain/lab_metric.dart';
import '../storage/app_database.dart';
import '../storage/database_provider.dart';
import '../utils/result.dart';

/// Builds a one-page doctor-visit summary PDF — current medications, the
/// latest labs with range flags, and recent events — and hands it to the
/// system share sheet.
class VisitSummaryPdf {
  VisitSummaryPdf(this._db);

  final AppDatabase _db;

  static const _blue = PdfColor.fromInt(0xFF0B57D0);
  static const _ink = PdfColor.fromInt(0xFF1F1F1F);
  static const _muted = PdfColor.fromInt(0xFF747775);

  Future<Result<void>> shareSummary() {
    return Result.guard(() async {
      final patient = await _db.patientDao.getPatient();
      final meds = await _db.medicationDao.watchActive().first;
      final labs = await _db.labDao.getAll();
      final events = await _db.timelineDao.getPage(limit: 12, offset: 0);
      final dateFormat = DateFormat('d MMM yyyy');

      final latestByMetric = <String, LabResult>{};
      for (final lab in labs) {
        latestByMetric.putIfAbsent(lab.metricCode, () => lab);
      }

      final doc = pw.Document();
      doc.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(36),
          build: (context) => [
            _header(patient, dateFormat),
            pw.SizedBox(height: 18),
            _sectionTitle('Current medications (${meds.length})'),
            _medsTable(meds),
            pw.SizedBox(height: 16),
            _sectionTitle('Latest laboratory values'),
            _labsTable(latestByMetric, dateFormat),
            pw.SizedBox(height: 16),
            _sectionTitle('Recent events'),
            _eventsList(events, dateFormat),
            pw.SizedBox(height: 20),
            pw.Text(
              'Generated by KidneyCare on '
              '${dateFormat.format(DateTime.now())}. '
              'For discussion with the treating team; not a medical '
              'document.',
              style: const pw.TextStyle(fontSize: 8, color: _muted),
            ),
          ],
        ),
      );

      await Printing.sharePdf(
        bytes: await doc.save(),
        filename:
            'kidneycare-visit-summary-${DateFormat('yyyy-MM-dd').format(DateTime.now())}.pdf',
      );
    });
  }

  pw.Widget _header(Patient? patient, DateFormat dateFormat) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: _blue, width: 2),
        ),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  patient?.name ?? 'Patient',
                  style: const pw.TextStyle(
                    fontSize: 20,
                    fontWeight: pw.FontWeight.bold,
                    color: _ink,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  [
                    if (patient != null) '${patient.age} yrs',
                    if (patient != null) patient.conditionSummary,
                    if (patient != null &&
                        patient.dialysisCenter.isNotEmpty)
                      patient.dialysisCenter,
                    if (patient != null && patient.dryWeightKg > 0)
                      'Dry weight ${patient.dryWeightKg.toStringAsFixed(1)} kg',
                  ].join('  ·  '),
                  style:
                      const pw.TextStyle(fontSize: 10, color: _muted),
                ),
                if (patient != null &&
                    patient.comorbidities.isNotEmpty)
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(top: 2),
                    child: pw.Text(
                      'Also has: ${patient.comorbidities}',
                      style: const pw.TextStyle(
                          fontSize: 10, color: _muted),
                    ),
                  ),
              ],
            ),
          ),
          pw.Text(
            'Visit summary\n${dateFormat.format(DateTime.now())}',
            textAlign: pw.TextAlign.right,
            style: const pw.TextStyle(fontSize: 10, color: _blue),
          ),
        ],
      ),
    );
  }

  pw.Widget _sectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        title.toUpperCase(),
        style: const pw.TextStyle(
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
          letterSpacing: 1,
          color: _blue,
        ),
      ),
    );
  }

  pw.Widget _medsTable(List<Medication> meds) {
    return pw.TableHelper.fromTextArray(
      headers: ['Medicine', 'Pattern', 'Purpose', 'Schedule', 'Doctor'],
      data: [
        for (final med in meds)
          [
            med.name,
            med.frequencyCode,
            med.purpose,
            med.scheduleNote,
            med.doctor,
          ],
      ],
      headerStyle: const pw.TextStyle(
          fontSize: 8.5, fontWeight: pw.FontWeight.bold, color: _ink),
      cellStyle: const pw.TextStyle(fontSize: 8.5, color: _ink),
      headerDecoration:
          const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF0F4F9)),
      cellPadding:
          const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      border: pw.TableBorder.all(
          color: const PdfColor.fromInt(0xFFE4E9F0), width: 0.5),
    );
  }

  pw.Widget _labsTable(
    Map<String, LabResult> latest,
    DateFormat dateFormat,
  ) {
    final rows = <List<String>>[];
    final flags = <bool>[];
    for (final metric in LabMetric.values) {
      final lab = latest[metric.code];
      if (lab == null) continue;
      final abnormal = metric.isAbnormal(lab.value);
      rows.add([
        metric.label,
        '${metric.format(lab.value)} ${metric.unit}',
        '${metric.format(metric.normalMin)}–'
            '${metric.format(metric.normalMax)}',
        abnormal ? (lab.value < metric.normalMin ? 'LOW' : 'HIGH') : 'ok',
        dateFormat.format(lab.takenAt),
      ]);
      flags.add(abnormal);
    }

    return pw.TableHelper.fromTextArray(
      headers: ['Metric', 'Value', 'Normal range', 'Flag', 'Taken'],
      data: rows,
      headerStyle: const pw.TextStyle(
          fontSize: 8.5, fontWeight: pw.FontWeight.bold, color: _ink),
      cellStyle: const pw.TextStyle(fontSize: 8.5, color: _ink),
      headerDecoration:
          const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF0F4F9)),
      cellPadding:
          const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      border: pw.TableBorder.all(
          color: const PdfColor.fromInt(0xFFE4E9F0), width: 0.5),
      cellDecoration: (index, data, rowNum) {
        final abnormal =
            rowNum >= 1 && rowNum <= flags.length && flags[rowNum - 1];
        return pw.BoxDecoration(
          color: abnormal
              ? const PdfColor.fromInt(0xFFFEF7E0)
              : PdfColors.white,
        );
      },
    );
  }

  pw.Widget _eventsList(
    List<TimelineEvent> events,
    DateFormat dateFormat,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        for (final event in events)
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 3),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.SizedBox(
                  width: 64,
                  child: pw.Text(
                    dateFormat.format(event.occurredAt),
                    style: const pw.TextStyle(
                        fontSize: 8.5, color: _muted),
                  ),
                ),
                pw.Expanded(
                  child: pw.RichText(
                    text: pw.TextSpan(
                      text: event.title,
                      style: const pw.TextStyle(
                        fontSize: 8.5,
                        fontWeight: pw.FontWeight.bold,
                        color: _ink,
                      ),
                      children: [
                        if (event.subtitle.isNotEmpty)
                          pw.TextSpan(
                            text: '  —  ${event.subtitle}',
                            style: const pw.TextStyle(
                              fontWeight: pw.FontWeight.normal,
                              color: _muted,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}

final visitSummaryPdfProvider = Provider<VisitSummaryPdf>((ref) {
  return VisitSummaryPdf(ref.watch(databaseProvider));
});
